# Generated by Django 4.1 on 2024-09-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="banners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="banners/")),
                ("alt_text", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enquirer_name", models.CharField(max_length=150)),
                ("enquirer_email", models.CharField(max_length=150)),
                ("enquiry_message", models.TextField()),
                ("enquiry_dateAndTime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("detail", models.TextField()),
                ("img", models.ImageField(null=True, upload_to="services/")),
            ],
        ),
        migrations.CreateModel(
            name="trainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, null=True)),
                ("password", models.CharField(max_length=100, null=True)),
                ("full_name", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("detail", models.TextField()),
                ("img", models.ImageField(null=True, upload_to="trainers/")),
            ],
        ),
        migrations.CreateModel(
            name="mealplan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscriber", models.CharField(max_length=100)),
                (
                    "mealtime",
                    models.CharField(
                        choices=[("B", "breakfast"), ("L", "lunch"), ("D", "dinner")],
                        default="B",
                        max_length=1,
                    ),
                ),
                ("meal", models.CharField(max_length=100)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mealplans",
                        to="main.trainer",
                    ),
                ),
            ],
        ),
    ]
