# Generated by Django 5.1 on 2024-08-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquirer_name', models.CharField(max_length=150)),
                ('enquirer_email', models.CharField(max_length=150)),
                ('enquiry_message', models.TextField()),
                ('enquiry_dateAndTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
