# Generated by Django 4.1 on 2024-08-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_trainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="passw",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="trainer",
            name="user",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
