# Generated by Django 4.1 on 2024-08-16 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_trainer_passw_trainer_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainer",
            old_name="user",
            new_name="usern",
        ),
    ]
