# Generated by Django 4.1 on 2024-08-16 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_rename_user_trainer_usern"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainer",
            old_name="passw",
            new_name="password",
        ),
        migrations.RenameField(
            model_name="trainer",
            old_name="usern",
            new_name="username",
        ),
    ]
